type ScriptName =
  | 'alarmfax'
  | 'autoCollapseBuildings'
  | 'countPatients'
  | 'countPossibleMissions'
  | 'customBuildingIcons'
  | 'customMapZoom'
  | 'customMissionIcons'
  | 'deleteNewestFmsAfterTime'
  | 'expandAssociationCards'
  | 'expandMapLegend'
  | 'fastMissionSpeed'
  | 'filterAaoEditVehicles'
  | 'filterMemberList'
  | 'hideAchievementcard'
  | 'hideBuildingIcons'
  | 'hideFreeText'
  | 'missionCounter'
  | 'missionHelper'
  | 'missionTime'
  | 'multipleStaffAssignment'
  | 'showOnlyLatestRadioMessage'
  | 'userBuildings'
  | 'userVehicles'
  | 'selectedVehicles';

export type { ScriptName };
