name: Deploy to server

on:
  release:
    types:
      - created

  push:
    branches:
      - main
    paths:
      - src/json/**.*

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: npm install
        run: npm install --save-dev
      - name: npm fund
        run: npm fund
      - name: Setup
        run: npm run setup
      - name: Gulp
        run: npm run gulp-build:prod
      - name: Rollup
        run: npm run rollup-build
      - name: Theme
        run: npm run prepare
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.strato.de
          username: sftp_script_manager_github@keineahnung.eu
          password: ${{ secrets.FTP_PW_GH }}
          port: 21
          local-dir: ./build/
          exclude: |
            **/views/**
